Line1: " &1&l============================================"
Line2: " "
Line3: " &a&lSite : &r&3&ohttp://maxime3399.fr"
Line4: " &6&lForum : &r&b&ohttp://maxime3399.fr/forum"
Line5: " &e&lBoutique : &r&9&ohttp://maxime3399.fr/?page_id=17"
Line6: " &2Bienvenue &b%player% &r&2sur &r&6M-Cube &r&2!"
Line7: " "
Line8: " &6>> &2&l1.12&r &aDISPONIBLE &r&3: &r&d&ohttp://maxime3399.fr/?p=247"
Line9: " "
Line10: " &1&l============================================"

#%player% >> Nom du joueur

Motd1 : "   &1&l=&r&9&l=&r&3&l=&r&b&l=&r &e&k||&r &6&lM-CUBE &r&e&k||&r &b&l=&r&3&l=&r&9&l=&r&1&l=&r  &5&oVersion &r&d>>  &r&21.12"
Motd2 : " &e&l&k|||||&r &2&l1.12 &r&6UPDATE &r&e&l&k|||||&r"

MaintenanceMessage : "&3Le serveur est en maintenance !"
CloseMessage: "&cLe serveur est fermé !"